<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Página Inicial Do Painel</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        .content {
            margin-top: 80px;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?=HOME;?>">Painel Administrativo</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">

            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>

<div class="container content">

        <div class="row">
          <?php require VIEWS . '/includes/message.phtml'; ?>
        </div>
        
       <div class="col-md-4 col-md-offset-4">
           <form action="<?=HOME;?>/auth/relembrar-senha" method="post">
               <div class="form-group">
                   <label for="exampleInputEmail1">Email</label>
                   <input type="email" class="form-control" name="email" placeholder="Escreva seu e-mail para enviarmos o lembrete">
               </div>
               <div class="row">
                  <div class="col-md-12">
                      <a href="<?=HOME;?>/auth/login">Voltar ao login</a>
                  </div>
               </div>
               <button type="submit" class="btn btn-default btn-success pull-right">Relembrar</button>
           </form>
       </div>
    </div>
</body>
</html>