<?php require VIEWS . '/includes/header.phtml';?>
	<div class="row">
		<div class="col-md-12">
			<h1>Usuário</h1>
			<a href="<?=HOME . '/admin/users/list';?>" class="btn btn-warning">
				Voltar
			</a>
			<hr>
		</div>
	</div>
	<div class="row">
		<?php require VIEWS . '/includes/message.phtml'; ?>
	</div>
	<div class="row">
		<form action="<?=HOME . '/admin/users/edit';?>" method="POST">

		  <div class="form-group">
		    <label for="exampleInputEmail1">Nome</label>
		    <input type="text" class="form-control" placeholder="Nome" name="name" value="<?=$user['name'];?>">
		  </div>

		  <div class="form-group">
		    <label for="exampleInputEmail1">Email</label>
		    <input type="email" class="form-control" placeholder="Email" name="email" value="<?=$user['email'];?>">
		  </div>
		  <div class="form-group">
		    <label for="exampleInputPassword1">Password</label>
		    <input type="password" class="form-control" placeholder="Password" name="password" placeholder="Se você deseja alterar a senha do usuário, preencha aqui!">
		  </div>
		 	
		  <input type="hidden" name="id" value="<?=$user['id'];?>">
		  <button type="submit" class="btn btn-success">Salvar</button>
		</form>
	</div>
<?php require VIEWS . '/includes/footer.phtml';?>